CXX =g++

CXXFLAGS = -Wall -Wextra -std=c++11

# FILES := $(wildcard test*)


myprogram : r_version.cpp
	  $(CXX) $(CXXFLAGS) -o myprogram r_version.cpp; 

# run: myprogram
# 	./myprogram $(FILES)


clean:
		rm -f myprogram
